/******************************************************************************/
/****         Generated by IBExpert 2023.1.3.1 09/11/2024 10:18:39         ****/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES WIN1252;

SET CLIENTLIB 'C:\Program Files\Firebird\Firebird_3_0\WOW64\fbclient.dll';

CREATE DATABASE 'localhost/3050:C:\Dados\Programacao\Sistema-Exemplo-Posto-ABC\Exe\Dados\PostoABC.FDB'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 16384
DEFAULT CHARACTER SET WIN1252 COLLATION WIN1252;



/******************************************************************************/
/****                              Generators                              ****/
/******************************************************************************/

CREATE GENERATOR GEN_ABASTECIMENTO START WITH 0 INCREMENT BY 1;
SET GENERATOR GEN_ABASTECIMENTO TO 0;

CREATE GENERATOR GEN_BOMBACOMBUSTIVEL START WITH 0 INCREMENT BY 1;
SET GENERATOR GEN_BOMBACOMBUSTIVEL TO 4;

CREATE GENERATOR GEN_TANQUE START WITH 0 INCREMENT BY 1;
SET GENERATOR GEN_TANQUE TO 2;



/******************************************************************************/
/****                                Tables                                ****/
/******************************************************************************/



CREATE TABLE ABASTECIMENTO (
    ABA_CODIGO      INTEGER NOT NULL,
    ABA_DATA        DATE NOT NULL,
    ABA_BCM_CODIGO  INTEGER NOT NULL,
    ABA_LITROS      DECIMAL(15,5),
    ABA_VALOR       DECIMAL(15,2),
    ABA_IMPOSTO     DECIMAL(15,2),
    ABA_VALORTOTAL  DECIMAL(15,2)
);

CREATE TABLE BOMBA_COMBUSTIVEL (
    BCM_CODIGO      INTEGER NOT NULL,
    BCM_TAN_CODIGO  INTEGER NOT NULL,
    BCM_DESCRICAO   VARCHAR(100) NOT NULL
);

CREATE TABLE TANQUE (
    TAN_CODIGO           INTEGER NOT NULL,
    TAN_DESCRICAO        VARCHAR(100) NOT NULL,
    TAN_TIPOCOMBUSTIVEL  CHAR(1) NOT NULL
);

INSERT INTO TANQUE (TAN_CODIGO, TAN_DESCRICAO, TAN_TIPOCOMBUSTIVEL) VALUES (1, 'GASOLINA', 'G');
INSERT INTO TANQUE (TAN_CODIGO, TAN_DESCRICAO, TAN_TIPOCOMBUSTIVEL) VALUES (2, 'ÓLEO DIESEL', 'D');


COMMIT WORK;

INSERT INTO BOMBA_COMBUSTIVEL (BCM_CODIGO, BCM_TAN_CODIGO, BCM_DESCRICAO) VALUES (1, 1, 'BOMBA 01');
INSERT INTO BOMBA_COMBUSTIVEL (BCM_CODIGO, BCM_TAN_CODIGO, BCM_DESCRICAO) VALUES (2, 1, 'BOMBA 02');
INSERT INTO BOMBA_COMBUSTIVEL (BCM_CODIGO, BCM_TAN_CODIGO, BCM_DESCRICAO) VALUES (3, 2, 'BOMBA 03');
INSERT INTO BOMBA_COMBUSTIVEL (BCM_CODIGO, BCM_TAN_CODIGO, BCM_DESCRICAO) VALUES (4, 2, 'BOMBA 04');


COMMIT WORK;



/******************************************************************************/
/****                             Primary keys                             ****/
/******************************************************************************/

ALTER TABLE ABASTECIMENTO ADD CONSTRAINT PK_ABASTECIMENTO PRIMARY KEY (ABA_CODIGO);
ALTER TABLE BOMBA_COMBUSTIVEL ADD CONSTRAINT PK_BOMBA_COMBUSTIVEL PRIMARY KEY (BCM_CODIGO);
ALTER TABLE TANQUE ADD CONSTRAINT PK_TANQUE PRIMARY KEY (TAN_CODIGO);


/******************************************************************************/
/****                             Foreign keys                             ****/
/******************************************************************************/

ALTER TABLE ABASTECIMENTO ADD CONSTRAINT FK_ABASTECIMENTO_1 FOREIGN KEY (ABA_BCM_CODIGO) REFERENCES BOMBA_COMBUSTIVEL (BCM_CODIGO) ON UPDATE CASCADE;
ALTER TABLE BOMBA_COMBUSTIVEL ADD CONSTRAINT FK_BOMBA_COMBUSTIVEL_1 FOREIGN KEY (BCM_TAN_CODIGO) REFERENCES TANQUE (TAN_CODIGO) ON UPDATE CASCADE;
